### ISSUE TITLE
Cannot run the program

### ISSUE THREAD

**Issue by johnnogent** [Conchylicultor/MusicGenerator#2]
Hello,
I cannot run the program, I have an error
File "../Deepstyle/MusicGenerator/deepmusic/musicdata.py", line 169, in _create_raw_songs
midi_files = [os.path.join(midi_dir, f) for f in os.listdir(midi_dir) if f.endswith(self.FILE_EXT)]
FileNotFoundError: [Errno 2] No such file or directory: '../Deepstyle/MusicGenerator/data/midi/ragtimemusic'
Can you help please?
John

**Comment by Conchylicultor** [comment]
It's probably because there is no midi file inside the `data/midi/ragtimemusic`. You have to create your own dataset with the song you want.

Also, on the last commits, I tried some experiments to change the song representation. For the different runs I did, the generated song looked quite random. So the program is currently not really usable.
